### ISSUE TITLE
missingDeps.some is not a function

### ISSUE THREAD

**Issue by ayxos** [gilbarbara/react-redux-saga-boilerplate#22]
I have this error when i try to run the app

```
Starting the development server...
/Users/marco.pajares/projects/react-redux-saga-boilerplate/tools/start.js:11
  throw err;
  ^

TypeError: missingDeps.some is not a function
    at compiler.plugin (/Users/marco.pajares/projects/react-redux-saga-boilerplate/node_modules/react-dev-utils/WatchMissingNodeModulesPlugin.js:25:23)
    at _err0 (eval at create (/Users/marco.pajares/projects/react-redux-saga-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at Promise.resolve.then.then.then.then.then.then.then.then.catch.then.then.then (/Users/marco.pajares/projects/react-redux-saga-boilerplate/node_modules/html-webpack-plugin/index.js:224:11)
```

**Comment by gilbarbara** [comment]
which installed version? Did you update webpack?
Make sure you running react-dev-utils@next fro webpack-4

**Comment by ayxos** [comment]
Works perfectly! thanks
